# Site settings
title: Squire Jekyll Theme
description: A clean and minimalistic Jekyll theme
baseurl: "/squire-jekyll-theme" # Leave empty if hosting at root, e.g., username.github.io
url: "https://s2bd.github.io" # Update to your domain when deploying
author: Your Name
email: your.email@example.com

# Build settings
theme: null
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Markdown settings
markdown: kramdown

# Collections
collections:
  pages:
    output: true
    permalink: /:path/

# Defaults for posts
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      permalink: /blog/:year/:month/:day/:title/
